package io.github.deltacv.papervision

/*
 * Autogenerated file! Do not manually edit this file, as
 * it is regenerated any time the build task is run.
 *
 * Based from PhotonVision PhotonVersion generator task
 */
@Suppress("UNUSED")
object Build {
    const val VERSION_STRING = "1.0.3-dev-241203-1134";
    const val STANDARD_VERSION_STRING = "1.0.3";
    const val BUILD_DATE = "2024-12-3 11:34:59";
    const val IS_DEV = true;
}