/*
 * PaperVision
 * Copyright (C) 2026 Sebastian Erives, deltacv
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.deltacv.papervision.node

import org.deltacv.papervision.gui.editor.CategorizedNodes
import org.deltacv.papervision.node.generated.PaperVisionPaperNodeMetadata
import org.deltacv.papervision.util.loggerForThis

@Suppress("UNCHECKED_CAST")
object PaperNodeRegistry {

    private val logger by loggerForThis()

    /**
     * Openly mutable map of categorized nodes used to register nodes.
     * Registered nodes will automatically be available in the editor list.
     */
    val nodes: CategorizedNodes = mutableMapOf()

    init {
        // Register nodes from metadata generated by KSP - PaperNodeAnnotationProcessor
        PaperVisionPaperNodeMetadata.registerAll()

        logger.info("Found ${nodes.values.sumOf { it.size }} registered nodes from @PaperNode metadata")
    }

    fun registerNode(nodeClass: Class<out Node<*>>, category: NodeCategory) {
        val list = nodes[category]

        val mutableNodes = nodes as MutableMap

        if (list == null) {
            mutableNodes[category] = mutableListOf(nodeClass)
        } else {
            list.add(nodeClass)
        }
    }

}



