package org.deltacv.visiongraph.serialization.v2

import org.deltacv.visiongraph.serialization.v2.generated.PaperVisionCodecTypeMetadata
import org.deltacv.visiongraph.util.loggerForThis
import kotlin.reflect.KClass

object CodecTypeRegistry {

    private val logger by loggerForThis()

    private val byName = mutableMapOf<String, CodecTypeEntry>()
    private val byClass = mutableMapOf<KClass<out DataCodec>, CodecTypeEntry>()

    init {
        // Register nodes from metadata generated by KSP - CodecTypeAnnotationProcessor
        PaperVisionCodecTypeMetadata.registerAll()

        logger.info("Found ${byName.size} registered DataCodecs from @CodecType metadata")
    }

    fun register(
        typeName: String,
        clazz: KClass<out DataCodec>,
        instantiator: (() -> DataCodec)? = null
    ) {
        require(typeName !in byName) { "Codec type name already registered: $typeName" }
        require(clazz !in byClass) { "Codec class already registered: ${clazz.qualifiedName}" }

        val codecTypeEntry = CodecTypeEntry(typeName, clazz, instantiator)
        byName[typeName] = codecTypeEntry
        byClass[clazz] = codecTypeEntry
    }

    fun create(typeName: String): DataCodec {
        val entry = byName[typeName]
            ?: throw NoSuchElementException("No codec registered with type name '$typeName'")

        return entry.instantiator?.invoke()
            ?: throw IllegalArgumentException("Codec type '$typeName' does not have an instantiator function")
    }

    fun isInstantiable(typeName: String): Boolean =
        byName[typeName]?.instantiator != null

    fun nameOf(clazz: KClass<out DataCodec>): String? =
        byClass[clazz]?.typeName

    private data class CodecTypeEntry(
        val typeName: String,
        val clazz: KClass<out DataCodec>,
        val instantiator: (() -> DataCodec)?
    )

}



