package org.deltacv.papervision.annotation.polymorphicserializable

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

class PolymorphicSerializableAnnotationProcessor(
    private val environment: SymbolProcessorEnvironment
) : SymbolProcessor {

    private var processed = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()
        processed = true

        val moduleName = environment.options["moduleName"] ?: ""

        val messages =
            resolver.getSymbolsWithAnnotation("org.deltacv.papervision.serialization.PolymorphicSerializable")
                .filterIsInstance<KSClassDeclaration>()
                .toList()

        if (messages.isEmpty()) return emptyList()

        val grouped = messages.groupBy { clazz ->
            clazz.annotations
                .first { it.shortName.asString() == "PolymorphicSerializable" }
                .arguments.first()
                .value as KSType
        }

        val objectBuilder = TypeSpec.objectBuilder("${moduleName}PolymorphicSerializableMetadata")

        grouped.forEach { (baseType, subclasses) ->
            val baseDeclaration = baseType.declaration
            val baseClassName = ClassName(
                baseDeclaration.packageName.asString(),
                baseDeclaration.simpleName.asString()
            )

            val builderClassName = ClassName("kotlinx.serialization.modules", "PolymorphicModuleBuilder")
                .parameterizedBy(baseClassName)

            val funName = "register${baseDeclaration.simpleName.asString()}Subclasses"

            val funcBuilder = FunSpec.builder(funName)
                .addParameter("builder", builderClassName)
                .beginControlFlow("with(builder)")

            subclasses.forEach {
                val subClassName = ClassName(it.packageName.asString(), it.simpleName.asString())
                funcBuilder.addStatement("subclass(%T::class, %T.serializer())", subClassName, subClassName)
            }

            funcBuilder.endControlFlow()

            objectBuilder.addFunction(funcBuilder.build())
        }

        val polymorphicSerializableMetadataPackage =
            environment.options["polymorphicSerializableMetadataPackage"] ?: "org.deltacv.papervision.generated"

        val fileSpec = FileSpec.builder(polymorphicSerializableMetadataPackage, "${moduleName}PolymorphicSerializableMetadata")
            .addFileComment("AUTO-GENERATED by PolymorphicSerializableAnnotationProcessor — do not edit")
            .addType(objectBuilder.build())
            .build()

        environment.codeGenerator.createNewFile(
            Dependencies(aggregating = true),
            polymorphicSerializableMetadataPackage,
            "${moduleName}PolymorphicSerializableMetadata"
        ).writer().use { writer ->
            fileSpec.writeTo(writer)
        }

        return emptyList()
    }
}



