import java.nio.file.Paths
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'com.google.devtools.ksp' version '2.3.4'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.10'
    id 'signing'
    id "com.vanniktech.maven.publish"
}

apply from: '../build.common.gradle'


def generatedSourcesDir = layout.buildDirectory.dir("generated/sources/buildinfo/java/main")

sourceSets {
    main {
        java {
            srcDirs += generatedSourcesDir
        }
    }
}

dependencies {
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinx_serialization_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinx_coroutines_version"

    compileOnly "io.github.spair:imgui-java-binding:$imgui_version" // platforms should add the "implementation" they need

    api 'org.deltacv:mai18n:1.2.0'

    implementation "org.java-websocket:Java-WebSocket:1.5.2"

    implementation("org.eclipse.jdt:org.eclipse.jdt.core:3.44.0")
    implementation("org.eclipse.platform:org.eclipse.text:3.14.500")

    implementation "com.google.code.gson:gson:$gson_version"
    implementation "io.github.classgraph:classgraph:$classgraph_version"

    implementation "org.deltacv:mackjpeg:$mackjpeg_version"

    api project(":Shared")
    ksp project(":AnnotationProcessor")
}

ksp {
    arg("moduleName", "PaperVision")

    arg("paperNodeClassesMetadataPackage", "org.deltacv.papervision.node.generated")
    arg("paperNodeClassesMetadataClassName", "PaperNodeMetadata")

    arg("codecTypeClassesMetadataPackage", "org.deltacv.papervision.serialization.v2.generated")
    arg("codecTypeClassesMetadataClassName", "CodecTypeMetadata")
}

tasks.register('writeBuildClass') {
    outputs.dir(generatedSourcesDir)

    doLast {
        String date = DateTimeFormatter.ofPattern("yyyy-M-d hh:mm:ss").format(LocalDateTime.now())

        def packageStr = "org.deltacv.papervision"
        def packagePath = packageStr.replace('.', '/')

        def outputDir = file("${generatedSourcesDir.get().asFile}/$packagePath")
        outputDir.mkdirs()

        def versionFile = file("${outputDir}/Build.kt")

        versionFile.text = """package $packageStr

/*
* Autogenerated file! Do not manually edit this file, as
* it is regenerated any time the build task is run.
*
* Based from PhotonVision PhotonVersion generator task
*/
object Build {
    const val VERSION_STRING = "$version";
    const val STANDARD_VERSION_STRING = "$standardVersion";
    const val BUILD_DATE = "$date";
    const val IS_DEV = ${version.contains("dev")};
}
"""
    }
}

tasks.matching { it.name == "compileKotlin" || it.name == "kspKotlin" }.configureEach {
    dependsOn writeBuildClass
}