plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.10'
    id 'signing'
    id "com.vanniktech.maven.publish"
    id 'com.google.devtools.ksp' version '2.3.4'
}

apply from: '../build.common.gradle'

dependencies {
    compileOnly "io.github.spair:imgui-java-binding:$imgui_version" // platforms should add the "implementation" they need
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinx_serialization_version"

    api "org.slf4j:slf4j-api:$slf4j_version"
    ksp project(":AnnotationProcessor")
}

ksp {
    arg("moduleName", "Shared")
    arg("polymorphicSerializableMetadataPackage", "org.deltacv.papervision.serialization.generated")
}



