/*
 * PaperVision
 * Copyright (C) 2026 Sebastian Erives, deltacv
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.deltacv.papervision.annotation.papernode

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*

class PaperNodeAnnotationProcessor(
    private val environment: SymbolProcessorEnvironment
) : SymbolProcessor {

    private val moduleName = environment.options["moduleName"] ?: ""
    private val packageName: String = environment.options["paperNodeClassesMetadataPackage"] ?: "org.deltacv.papervision.node.generated"
    private val fileName: String = moduleName + (environment.options["paperNodeClassesMetadataClassName"] ?: "PaperNodeMetadata")

    private val paperNodeRegistryClass = ClassName(
        "org.deltacv.papervision.node",
        "PaperNodeRegistry"
    )

    private val nodeCategoryClass = ClassName(
        "org.deltacv.papervision.node",
        "NodeCategory"
    )

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotatedSymbols = resolver.getSymbolsWithAnnotation("org.deltacv.papervision.node.PaperNode")

        val classList = annotatedSymbols.filterIsInstance<KSClassDeclaration>()

        generateRegistrationFile(classList)

        return emptyList()
    }

    private fun generateRegistrationFile(classes: Sequence<KSClassDeclaration>) {
        val entries = classes.map { cls ->
            val annotation = cls.annotations.first { it.shortName.asString() == "PaperNode" }
            val categoryDecl = annotation.arguments
                .first { it.name?.asString() == "category" }
                .value as KSClassDeclaration

            val className = ClassName(cls.packageName.asString(), cls.simpleName.asString())
            className to categoryDecl.simpleName.asString()
        }.toList()

        val sourceFiles = classes.map { it.containingFile!! }.toList()

        val registerAllFun = FunSpec.builder("registerAll")
            .also { func ->
                for ((className, category) in entries) {
                    func.addStatement(
                        "%T.registerNode(%T::class.java,·%T.%L)",
                        paperNodeRegistryClass,
                        className,
                        nodeCategoryClass,
                        category
                    )
                }
            }
            .build()

        val objectSpec = TypeSpec.objectBuilder(fileName)
            .addFunction(registerAllFun)
            .build()

        val fileSpec = FileSpec.builder(packageName, fileName)
            .addFileComment("AUTO-GENERATED by PaperNodeAnnotationProcessor — do not edit")
            .addType(objectSpec)
            .build()

        val dependencies = Dependencies(aggregating = true, *sourceFiles.toTypedArray())

        try {
            val file = environment.codeGenerator.createNewFile(
                dependencies,
                packageName = packageName,
                fileName = fileName,
                extensionName = "kt"
            )
            file.bufferedWriter().use { fileSpec.writeTo(it) }
        } catch (_: Exception) {
            // ignore duplicate file generation on incremental builds
        }
    }
}



