/*
 * VisionGraph
 * Copyright (C) 2026 Sebastian Erives, deltacv
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.deltacv.visiongraph.node

import org.deltacv.visiongraph.node.generated.PaperVisionPaperNodeMetadata
import org.deltacv.visiongraph.util.loggerForThis
import kotlin.reflect.KClass
import kotlin.reflect.full.findAnnotation
import kotlin.reflect.full.primaryConstructor

typealias CategorizedNodes = Map<NodeCategory, MutableList<KClass<out Node<*>>>>

data class NodeEntry(
    val nodeClass: KClass<out Node<*>>,
    val category: NodeCategory,
    val instantiator: (() -> Node<*>)?
)

@Suppress("UNCHECKED_CAST")
object PaperNodeRegistry {

    private val logger by loggerForThis()

    /**
     * Flat map of all registered node entries, keyed by KClass.
     * Populated at startup by the KSP-generated metadata.
     */
    private val entries = mutableMapOf<KClass<out Node<*>>, NodeEntry>()

    /**
     * Categorized view — the same data as [entries] but grouped for the UI.
     * Registered nodes will automatically be available in the editor list.
     */
    val nodes: CategorizedNodes = mutableMapOf()

    init {
        // Register nodes from metadata generated by KSP - PaperNodeAnnotationProcessor
        PaperVisionPaperNodeMetadata.registerAll()

        logger.info("Found ${entries.size} registered nodes from @PaperNode metadata")
    }

    /**
     * Register a node class with an optional instantiator lambda.
     * Called from KSP-generated code.
     */
    fun registerNode(
        nodeClass: KClass<out Node<*>>,
        category: NodeCategory,
        instantiator: (() -> Node<*>)? = null
    ) {
        val entry = NodeEntry(nodeClass, category, instantiator)
        entries[nodeClass] = entry

        val mutableNodes = nodes as MutableMap
        val list = mutableNodes.getOrPut(category) { mutableListOf() }
        list.add(nodeClass)
    }

    /**
     * Instantiate a node using the registered instantiator if available,
     * falling back to reflection otherwise.
     * @param nodeClass The KClass of the node to instantiate.
     * @return The node instance, or null if instantiation fails.
     */
    fun instantiate(nodeClass: KClass<out Node<*>>): Node<*>? {
        val instantiator = entries[nodeClass]?.instantiator
        return if (instantiator != null) {
            try {
                instantiator()
            } catch (e: Exception) {
                logger.warn("Registered instantiator for ${nodeClass.simpleName} threw an exception", e)
                null
            }
        } else {
            try {
                nodeClass.primaryConstructor?.call()
            } catch (e: Exception) {
                logger.warn("Error while dynamically instantiating node class ${nodeClass.qualifiedName}", e)
                null
            }
        }
    }
}

val KClass<out Node<*>>.paperNodeAnnotation: PaperNode?
    get() = this.findAnnotation<PaperNode>()
